services:
  api:
    image: "abdelhak245/multi-container-app:latest"
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: "mongo:latest"
    volumes: 
      - mongodb_volume:/data/db 
volumes:
  mongodb_volume: