name: Multi-Container Application
on: [push]
jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      ansibleChanged: ${{ steps.filter.outputs.ansible }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          ansible:
            - 'ansible/**'
  apply_ansible_playbook:
    runs-on: ubuntu-latest
    needs: paths-filter
    if: needs.paths-filter.outputs.ansibleChanged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v7
        with:
            playbook: playbook.yml
            directory: ./ansible/
            key: ${{secrets.SSH_PRIVATE_KEY}}