name: Multi-Container Application
on: [push]
jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      ansibleChanged: ${{ steps.filter.outputs.ansible }}
      appChanged: ${{ steps.filter.outputs.app }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          ansible:
            - 'ansible/**'
          app:
            - 'app/**'
  apply_ansible_playbook:
    runs-on: ubuntu-latest
    needs: paths-filter
    if: needs.paths-filter.outputs.ansibleChanged == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v7
        with:
            playbook: playbook.yml
            directory: ./ansible/
            key: ${{secrets.SSH_PRIVATE_KEY}}
  build_and_deploy_to_dockerHub:
    runs-on: ubuntu-latest
    needs: paths-filter
    if: needs.paths-filter.outputs.appChanged == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:app"
          push: true
          tags: | 
            ${{ secrets.DOCKERHUB_USERNAME }}/multi-container-app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/multi-container-app:${{github.sha}}