name: Multi-Container Application
on: [push]
jobs:
  apply_ansible_playbook:
    runs-on: ubuntu-latest
    steps:
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v7
        with:
            playbook: playbook.yml
            directory: ./ansible/
            key: ${{secrets.SSH_PRIVATE_KEY}}